### ISSUE TITLE
Formatting discrepancies with IMDb data relative to originals

### ISSUE THREAD

**Issue by allenschmaltz** [allenai/contrast-sets#15]
FYI--

When adding your IMDb data to my experiments here (https://arxiv.org/pdf/1906.01154.pdf), I noticed that there are some non-verbatim matches (on the order of ~26 out of 488) relative to the originals in https://github.com/acmi-lab/counterfactually-augmented-data (as a result of dropped special characters):

For example, Row 40 of https://github.com/allenai/contrast-sets/blob/master/IMDb/data/test_original.tsv does not exactly match line 183 of https://github.com/acmi-lab/counterfactually-augmented-data/blob/master/sentiment/orig/test.tsv because of dropped special characters.

Also, for example, see the diff with clichés->clichs in row 363 (test.tsv) vs. row 116 (test_original.tsv).

Also, as an aside, your IMDb data is double quote-escaped with depth 2, unlike the original.

**Comment by matt-gardner** [comment]
Thanks @allenschmaltz. @Eric-Wallace, can you look into?

**Comment by ruiqi-zhong** [comment]
The original file seems to have 3 major problems. 1) quotation formatting is wrong 2) non-English alphabets like "cliché" are missing 3) line changes are missing.  Attached (below) is my manual fix. I use the Kaggle data (https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews) as the reference, find out each place where the original differs from the Kaggle dataset, edit  "_original" Text to match the Kaggle dataset and apply the same editing to the contrast set. 

[dev_contrast.txt](https://github.com/allenai/contrast-sets/files/4843738/dev_contrast.txt)
[dev_original.txt](https://github.com/allenai/contrast-sets/files/4843739/dev_original.txt)
[test_contrast.txt](https://github.com/allenai/contrast-sets/files/4843740/test_contrast.txt)
[test_original.txt](https://github.com/allenai/contrast-sets/files/4843741/test_original.txt)

Feel free to fix the datasets with these files. (I cannot guarantee that the fixes on the contrast sets are correct, though, because I have no ground truth.)

**Comment by Eric-Wallace** [comment]
Hi. I've talked with Ruiqi about this offline a bit. I will take a look at his manual fixes and see if I can find any issues. Then, I will merge the new files into the main repo and close this issue.

**Comment by matt-gardner** [comment]
Thanks @Eric-Wallace!

**Comment by Eric-Wallace** [comment]
Just added Ruiqi's files, feel free to merge and close this issue @matt-gardner . Thanks all.
